#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import sys
from pathlib import Path
# Assuming 'rich_argparse' is a library used for formatting
from rich_argparse import RichHelpFormatter 
import os # Added for potential future use, standard practice in CLIs

# =========================================================
# Shared parsers
# ---------------------------------------------------------
# NOTE: These modules must exist in your postgwas project
# =========================================================
from postgwas.clis.common_cli import (
    get_defaultresourse_parser,
    get_common_out_parser,
    get_common_imputation_parser,
    get_bcftools_binary_parser
)
# NOTE: These modules must exist in your postgwas project
from postgwas.utils.main import validate_path
from postgwas.imputation.workflows import run_sumstat_imputation_direct
from postgwas.harmonisation.cli import run_harmonisation


# ---------------------------------------------------------
# DIRECT-MODE INPUT PARSER
# ---------------------------------------------------------
def get_imputation_direct_inputs_parser(add_help=False):
    """
    Inputs required for DIRECT imputation mode.
    (Output directory handled by get_common_out_parser)
    """
    # NOTE: add_help=False is used here so this parser doesn't
    # conflict when its arguments are grouped into the main parser.
    parser = argparse.ArgumentParser(add_help=add_help) 

    grp = parser.add_argument_group("Direct Mode Inputs")
    grp.add_argument(
        "--predld_input_dir",
        metavar=" ",
        type=validate_path(must_exist=True, must_be_dir=True),
        help=(
            "Directory containing per-chromosome formatted summary stats "
            "in PRED-LD compatible format (generated by postgwas formatter)."
        ),
    )
    return parser


# =========================================================
# MAIN CLI (DIRECT-ONLY, NO PIPELINE)
# =========================================================
def main():

    # -----------------------------------------------------
    # Top-level parser (Direct-only program)
    # -----------------------------------------------------
    # CRITICAL FIX: Removed add_help=False from here and removed 
    # the manual -h/--help addition below to fix the ArgumentError.
    parser = argparse.ArgumentParser( 
        prog="postgwas-imputation",
        description="PostGWAS summary-statistics imputation (DIRECT mode only).",
        formatter_class=RichHelpFormatter,
        parents=[
            get_defaultresourse_parser(),
            get_common_out_parser(),
            get_common_imputation_parser(),
            get_imputation_direct_inputs_parser(),
            get_bcftools_binary_parser()
        ],
    )

    # --- REMOVED THE CONFLICTING MANUAL -h/--help ADDITION ---
    # The default ArgumentParser automatically handles -h/--help.

    # If no arguments provided → show help
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(0)

    # Parse arguments
    args = parser.parse_args()

    # -----------------------------------------------------
    # Validate required inputs
    # -----------------------------------------------------
    missing = []

    # Check for the required 'predld_input_dir'
    if not hasattr(args, "predld_input_dir") or args.predld_input_dir is None:
        missing.append("--predld_input_dir")

    if missing:
        print("\n❗ Missing required arguments: " + ", ".join(missing) + "\n")
        parser.print_help()
        sys.exit(1)

    # -----------------------------------------------------
    # Run the DIRECT workflow
    # -----------------------------------------------------
    # Call the main imputation function with parsed arguments
    combined_df, corr_df,config_path=run_sumstat_imputation_direct(args) 
# =========================================================
# Entry point
# =========================================================
if __name__ == "__main__":
    # Ensure this line number (104) is correctly referenced in the final code
    main()