#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import sys
import os
from pathlib import Path
from rich_argparse import RichHelpFormatter

# =========================================================
# Shared parsers (imported, not redefined)
# =========================================================
from postgwas.clis.common_cli import (
    get_defaultresourse_parser,
    get_common_out_parser,
    get_common_imputation_parser
)
from postgwas.utils.main import validate_path
from postgwas.imputation.workflows import (
    run_sumstat_imputation_direct,
    run_sumstat_imputation_pipeline
)


def get_imputation_direct_inputs_parser(add_help=False):
    """
    Inputs needed for DIRECT mode.

    Note:
      - Output directory is provided by get_common_out_parser()
        (we use args.outdir there).
    """
    parser = argparse.ArgumentParser(add_help=add_help)
    grp = parser.add_argument_group("Imputation Direct-Mode Inputs")
    grp.add_argument(
        "--predld_input_dir",
        metavar=" ",
        type=validate_path(must_exist=True, must_be_dir=True),
        required=True,
        help=(
            "Directory containing per-chromosome GWAS summary statistic files "
            "in PRED-LD compatible format. "
            "These should be generated by the postgwas formatter module."
        ),
    )
    return parser


# =========================================================
# MAIN CLI
# =========================================================
def main():
    top = argparse.ArgumentParser(
        prog="postgwas-imputation",
        description="PostGWAS summary-statistics imputation module.",
        formatter_class=RichHelpFormatter,
    )

    sub = top.add_subparsers(dest="mode", help="Choose execution mode")

    # ------------- DIRECT MODE -------------
    direct = sub.add_parser(
        "direct",
        help="Run a single imputation tool (no mandatory post-processing).",
        parents=[
            get_defaultresourse_parser(),
            get_common_out_parser(),
            get_common_imputation_parser(add_help=False),
            get_imputation_direct_inputs_parser(add_help=False),
        ],
        formatter_class=RichHelpFormatter,
    )
    direct.set_defaults(func=run_sumstat_imputation_direct)

    # ------------- PIPELINE MODE -----------
    pipeline = sub.add_parser(
        "pipeline",
        help="Run imputation + standard post-processing (e.g. merge, QC, correlations).",
        parents=[
            get_defaultresourse_parser(),
            get_common_out_parser(),
            get_common_imputation_parser(add_help=False),
        ],
        formatter_class=RichHelpFormatter,
    )
    pipeline.set_defaults(func=run_sumstat_imputation_pipeline)

    # ------------- EXECUTION ---------------
    args = top.parse_args()

    # No subcommand → print top-level help
    if args.mode is None:
        top.print_help()
        sys.exit(0)

    # If only "direct" or "pipeline" is given without further args, show subcommand help
    if len(sys.argv) == 2 and args.mode in ["direct", "pipeline"]:
        if args.mode == "direct":
            direct.print_help()
        else:
            pipeline.print_help()
        sys.exit(0)

    # Dispatch to the selected workflow
    args.func(args)


if __name__ == "__main__":
    main()