enabled: false
significance_threshold: 5.0e-8
suggestive_threshold: 1.0e-5
autosome_count: 22
minimum_af: 0.0
minimum_neglog10_p: 2
loglog_pvalue: 10
cytoband_ratio: 25
maximum_height: null
chromosome_spacing: 20
width: 7.0
height: null
font_size: 12
allelic_shift: false
flag_coding: false
file_format: pdf
