#!/usr/bin/env python3
"""
PostGWAS — FLAMES
Fine-mapped Locus Assessment Model of Effector geneS

Supports:

  • DIRECT MODE:
        Run FLAMES using precomputed SuSiE, MAGMA, and PoPS outputs.

This CLI is aligned with the PostGWAS ecosystem.
"""
from pathlib import Path
import argparse
import sys
from rich_argparse import RichHelpFormatter, ArgumentDefaultsRichHelpFormatter

from postgwas.clis.common_cli import safe_parse_args

# Allowed shared builders (must accept add_help=False if used in parents list)
from postgwas.clis.common_cli import (
    get_defaultresourse_parser,
    get_common_out_parser,
    get_flames_common_parser
)

from postgwas.flames.workflows import (
    run_flames_direct,
)

from postgwas.utils.main import validate_path


# ============================================================
# FLAMES DIRECT MODE ARGUMENTS (Merged into top-level parser)
# ============================================================
def get_flames_direct_parser(add_help=False):
    """
    FLAMES DIRECT MODE
    User provides:
      • SuSiE credible sets
      • MAGMA gene-level outputs
      • PoPS scores
    Defines the arguments, but does not enforce 'required=True'
    as they will be enforced at the top-level parser.
    """
    parser = argparse.ArgumentParser(add_help=add_help)

    grp = parser.add_argument_group("FLAMES Direct Input Files")

    grp.add_argument(
        "--finemap_cred_dir",
        metavar="",
        type=validate_path(must_exist=True, must_be_dir=True),
        # Note: 'required=True' is enforced in main() below
        help=(
            "Folder containing SuSiE credible-set summary files.\n"
            "Must be produced by PostGWAS fine-mapping (SuSiE module)."
        ),
    )

    grp.add_argument(
        "--magma_genes_out",
        metavar="",
        type=validate_path(must_exist=True, must_be_file=True),
        help=(
            "MAGMA gene-level association results file.\n"
            "Typically the output:  {prefix}.genes.out"
        ),
    )

    grp.add_argument(
        "--magma_tissue_covar_results",
        metavar="",
        type=validate_path(must_exist=True, must_be_file=True),
        help=(
            "MAGMA gene-property/tissue covariate output file.\n"
            "Typically produced by MAGMA covariate analysis:  {prefix}.gsa.out"
        ),
    )

    grp.add_argument(
        "--pops_score_file",
        metavar="",
        type=validate_path(must_exist=True, must_be_file=True),
        help=(
            "PoPS gene score file containing gene-level prioritisation values.\n"
            "Must be generated by the PostGWAS PoPS module."
        ),
    )

    # --------------------------------------------------------
    # Optional for Direct Mode
    # --------------------------------------------------------
    opt = parser.add_argument_group("Optional Settings")

    opt.add_argument(
        "--label",
        metavar="",
        help="Optional label to tag this FLAMES run.",
    )

    opt.add_argument(
        "--dry_run",
        action="store_true",
        help="Validate inputs but do not execute FLAMES.",
    )

    return parser


# ============================================================
# MAIN ENTRY POINT (Direct Mode Only)
# ============================================================
def main():

    # 1. Setup the single, top-level parser, inheriting all required components.
    parser = argparse.ArgumentParser(
        prog="flames",
        description=(
            "🔥 [bold cyan]FLAMES — Fine-mapped Locus Assessment Model of Effector geneS[/bold cyan]\n\n"
            "Effector gene prioritisation using SuSiE credible sets, MAGMA gene scores, "
            "and PoPS gene features. (Direct Mode Only)"
        ),
        formatter_class=ArgumentDefaultsRichHelpFormatter,
        parents=[
            get_defaultresourse_parser(),
            get_common_out_parser(),
            get_flames_direct_parser(),
            get_flames_common_parser(),
        ],
    )

    # If no arguments provided → show help
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(0)

    # Parse all arguments
    args = parser.parse_args()

    # 4. Dispatch the run_flames_direct function as the default action
    run_flames_direct(args)


if __name__ == "__main__":
    main()
    
    