#!/usr/bin/env python3
"""
PostGWAS — FLAMES
Fine-mapped Locus Assessment Model of Effector geneS

Supports:

  • DIRECT MODE:
        Run FLAMES using precomputed SuSiE, MAGMA, and PoPS outputs.

  • PIPELINE MODE:
        Full workflow:
            Harmonisation → LD Blocks → QC → Formatter →
            SuSiE → MAGMA → PoPS → FLAMES

This CLI is aligned with the PostGWAS ecosystem.
"""
from pathlib import Path
import argparse
import sys
from rich_argparse import RichHelpFormatter, ArgumentDefaultsRichHelpFormatter

from postgwas.clis.common_cli import safe_parse_args

# Allowed shared builders (must accept add_help=False)
from postgwas.clis.common_cli import (
    get_defaultresourse_parser,
    get_inputvcf_parser,
    get_genomeversion_parser,
    get_common_out_parser,
    get_common_sumstat_filter_parser,
    get_common_susie_arguments,
    get_common_magma_assoc_parser,
    get_common_pops_parser,
    get_finemap_method_parser,
    get_magma_binary_parser,
    get_plink_binary_parser,
    get_bcftools_binary_parser,
    get_flames_common_parser
)

from postgwas.flames.workflows import (
    run_flames_direct,
    run_flames_pipeline,
)

from postgwas.utils.main import validate_path


# ============================================================
# DIRECT MODE PARSER
def get_flames_direct_parser(add_help=False):
    """
    FLAMES DIRECT MODE
    User provides:
      • SuSiE credible sets
      • MAGMA gene-level outputs
      • PoPS scores
    No SuSiE/MAGMA/PoPS computation is performed here.
    """
    parser = argparse.ArgumentParser(add_help=add_help)

    grp = parser.add_argument_group("FLAMES Direct Input Files")

    grp.add_argument(
        "--finemap_cred_dir",
        metavar="",
        type=validate_path(must_exist=True, must_be_dir=True),
        help=(
            "Folder containing SuSiE credible-set summary files.\n"
            "Must be produced by PostGWAS fine-mapping (SuSiE module)."
        ),
    )

    grp.add_argument(
        "--magma_genes_out",
        metavar="",
        type=validate_path(must_exist=True, must_be_file=True),
        help=(
            "MAGMA gene-level association results file.\n"
            "Typically the output:  {prefix}.genes.out"
        ),
    )

    grp.add_argument(
        "--magma_tissue_covar_results",
        metavar="",
        type=validate_path(must_exist=True, must_be_file=True),
        help=(
            "MAGMA gene-property/tissue covariate output file.\n"
            "Typically produced by MAGMA covariate analysis:  {prefix}.gsa.out"
        ),
    )

    grp.add_argument(
        "--pops_score_file",
        metavar="",
        type=validate_path(must_exist=True, must_be_file=True),
        help=(
            "PoPS gene score file containing gene-level prioritisation values.\n"
            "Must be generated by the PostGWAS PoPS module."
        ),
    )

    # --------------------------------------------------------
    # Optional for Direct Mode
    # --------------------------------------------------------
    opt = parser.add_argument_group("Optional Settings")

    opt.add_argument(
        "--label",
        metavar="",
        help="Optional label to tag this FLAMES run.",
    )

    opt.add_argument(
        "--dry_run",
        action="store_true",
        help="Validate inputs but do not execute FLAMES.",
    )

    return parser




# ============================================================
# MAIN ENTRY POINT
# ============================================================
def main():

    top = argparse.ArgumentParser(
        prog="flames",
        description=(
            "🔥 [bold cyan]FLAMES — Fine-mapped Locus Assessment Model of Effector geneS[/bold cyan]\n\n"
            "Effector gene prioritisation using SuSiE credible sets, MAGMA gene scores, "
            "and PoPS gene features."
        ),
        formatter_class=RichHelpFormatter,
    )

    sub = top.add_subparsers(dest="mode", help="Choose execution mode")

    # DIRECT
    direct = sub.add_parser(
        "direct",
        help="Run FLAMES using precomputed SuSiE, MAGMA and PoPS outputs.",
        parents=[
            get_defaultresourse_parser(),
            get_common_out_parser(),
            get_flames_direct_parser(add_help=False),
            get_flames_common_parser()
        ],
        formatter_class=ArgumentDefaultsRichHelpFormatter,
    )
    direct.set_defaults(func=run_flames_direct)

    # PIPELINE
    pipeline = sub.add_parser(
        "pipeline",
        help="Run full PostGWAS → SuSiE → MAGMA → PoPS → FLAMES pipeline.",
        parents=[
            get_defaultresourse_parser(),
            get_inputvcf_parser(),
            get_genomeversion_parser(),
            get_common_sumstat_filter_parser(add_help=False),
            get_common_susie_arguments(add_help=False),
            get_finemap_method_parser(add_help=False),
            get_magma_binary_parser(add_help=False),
            get_plink_binary_parser(add_help=False),
            get_bcftools_binary_parser(add_help=False),
            get_common_magma_assoc_parser(add_help=False),
            get_common_pops_parser(add_help=False),
            get_flames_common_parser(),
            get_common_out_parser(),
            
        ],
        formatter_class=ArgumentDefaultsRichHelpFormatter,
    )
    pipeline.set_defaults(func=run_flames_pipeline)

    # SAFE PARSE
    args = safe_parse_args(top)

    # -------------------------------
    # AUTO HELP FALLBACKS
    # -------------------------------
    if args.mode == "direct" and len(sys.argv) == 2:
        direct.parse_args(["--help"])
        sys.exit(0)

    if args.mode == "pipeline" and len(sys.argv) == 2:
        pipeline.parse_args(["--help"])
        sys.exit(0)

    # Dispatch
    if hasattr(args, "func"):
        args.func(args)
    else:
        top.print_help()



if __name__ == "__main__":
    main()
