"""Three-stage validation of a GWAS harmonisation configuration.

Plan v3 Part 2.  Validation is split into three stages so that a mistyped
column name costs a second rather than a full parse of a ten-million-row file:

    stage 1  validate_config(cfg, policies)                 config only, no file read
    stage 2  validate_header(cfg, sumstat_path, policies)   reads one line
    stage 3  validate_content(cfg, df, policies)            needs the parsed data

Every stage returns ``(is_valid, problems)`` and every stage collects **all**
problems; none stops at the first.  Each problem is a :class:`Problem` record
carrying ``config_key``, ``configured_value``, ``issue`` and ``suggestion``, so
the error message is generated by :func:`format_problems` rather than
hand-written per case.

"""

import bz2
import csv
import difflib
import gzip
import lzma
import os
import zipfile
from collections import Counter, OrderedDict
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Sequence, Tuple

import polars as pl

from postgwas.core.io.delimiters import (
    delimiter_character,
    detect_delimiter,
    open_text,
    resolve_delimiter,
)
from postgwas.core.values import MISSING_TEXT

from postgwas.modules.harmonisation.policies import (
    Policies,
    PolicyError,
    default_policies,
    load_policies,
)
from postgwas.modules.harmonisation.resource_paths import (
    matching_external_resource_files,
    validate_external_resource_spec,
)
from postgwas.modules.harmonisation.shared.runtime import (
    emit_high_visibility_warning,
    emit_message,
)
from postgwas.modules.harmonisation.shared.variant_columns import (
    has_canonical_variant_columns,
)


__all__ = [
    "Problem",
    "ConfigError",
    "COLUMN_CONFIG_KEYS",
    "NUMERIC_COLUMN_KEYS",
    "CATEGORY_HEADINGS",
    "validate_config",
    "validate_header",
    "validate_content",
    "format_problems",
    "read_summary_statistics_header",
]


# ----------------------------------------------------------------------
# The config keys that name a column in the input file (plan 2.3).
# ----------------------------------------------------------------------
COLUMN_CONFIG_KEYS = (
    "chr_col",
    "pos_col",
    "snp_id_col",
    "ea_col",
    "oa_col",
    "eaf_col",
    "beta_or_col",
    "se_col",
    "imp_z_col",
    "pval_col",
    "ncase_col",
    "ncontrol_col",
    "imp_info_col",
    "chr_pos_col",
)

# Of those, the ones that must hold numbers once parsed.
NUMERIC_COLUMN_KEYS = (
    "pos_col",
    "eaf_col",
    "beta_or_col",
    "se_col",
    "imp_z_col",
    "pval_col",
    "ncase_col",
    "ncontrol_col",
    "imp_info_col",
)

# Files a config may name.  (key, human description, is_required)
FILE_CONFIG_KEYS = (
    ("sumstat_file", "the GWAS summary statistics file", True),
    ("eaffile", "the external allele-frequency file", False),
    ("infofile", "the external imputation-INFO file", False),
    ("default_comparison_af_file", "the comparison allele-frequency panel", False),
    ("default_dbsnp", "the dbSNP reference", False),
    ("dbsnp", "the dbSNP reference", False),
    ("fasta", "the reference FASTA", False),
    ("reference_fasta", "the reference FASTA", False),
    ("chain_file", "the liftover chain file", False),
)

# Values that mean "not configured".
MISSING_TOKENS = MISSING_TEXT

_PATH_SUFFIXES = (
    ".gz", ".bgz", ".bz2", ".xz", ".lzma", ".zip",
    ".tsv", ".txt", ".csv", ".vcf", ".bcf", ".bed",
    ".fa", ".fasta", ".fai", ".chain", ".json", ".yaml", ".yml", ".parquet",
)

# One heading per problem category.  The report is generated from these.
CATEGORY_HEADINGS = OrderedDict(
    (
        ("missing_key", "Mandatory config entries are empty or NA:"),
        ("missing_field", "Required information is not available from any source:"),
        ("bad_value", "Config values cannot be used as given:"),
        ("file_missing", "Files named in the config cannot be used:"),
        (
            "external_column_missing",
            "External files do not contain the column they are configured to supply:",
        ),
        ("output", "The output location cannot be used:"),
        ("policy", "Policy settings are not valid:"),
        ("file_unreadable", "The input file could not be read:"),
        ("column_not_found", "The config names columns that are not in the input file:"),
        (
            "ambiguous_mapping",
            "Two config keys point at the same column, which is almost certainly a mistake:",
        ),
        ("duplicate_header", "The input file carries the same column name twice:"),
        ("all_null", "Configured columns are present in the data but hold no values:"),
        ("not_numeric", "Columns that must hold numbers contain text that will not parse:"),
        ("no_variants", "No variants survive the basic coordinate and allele checks:"),
    )
)


# ======================================================================
# The record every message is generated from
# ======================================================================
@dataclass(frozen=True)
class Problem(object):
    """One thing that is wrong, described well enough to be fixed.

    ``config_key``       the config entry at fault (or a comma-joined list of
                         them, for problems that involve more than one).
    ``configured_value`` what the config said.  ``None`` renders the issue as a
                         complete sentence instead of ``key = value  issue``.
    ``issue``            what is wrong with it, in plain English.
    ``suggestion``       what to do about it.
    """

    config_key: str
    configured_value: Any
    issue: str
    suggestion: str = ""
    category: str = "bad_value"
    stage: str = ""
    severity: str = "error"
    #: when the issue is already a complete sentence naming the keys itself,
    #: render it on its own instead of prefixing the key again.
    standalone: bool = False

    # -- rendering ----------------------------------------------------
    def rendered_value(self) -> str:
        if self.configured_value is None:
            return ""
        return "'%s'" % (self.configured_value,)

    def line(self, key_width: int = 0, value_width: int = 0) -> str:
        issue = self.issue.rstrip().rstrip(".")
        if self.standalone:
            text = "%s." % (issue,)
        elif self.configured_value is None:
            text = "%s : %s." % (self.config_key.ljust(key_width), issue)
        else:
            text = "%s = %s %s." % (
                self.config_key.ljust(key_width),
                self.rendered_value().ljust(value_width),
                issue,
            )
        if self.suggestion:
            text = "%s  %s" % (text, self.suggestion)
        return text.rstrip()

    def __str__(self) -> str:
        return self.line()


class ConfigError(Exception):
    """Raised instead of ``sys.exit(1)`` so a caller can catch it (plan 2.5).

    ``SystemExit`` derives from ``BaseException``, so ``except Exception`` in
    ``cli.py`` never sees it and one bad dataset kills the whole batch.
    """

    def __init__(self, problems, message: Optional[str] = None):
        self.problems = list(problems or [])
        if message is None:
            message = format_problems(self.problems)
        super(ConfigError, self).__init__(message)


# ======================================================================
# Small helpers
# ======================================================================
def _clean(value: Any) -> str:
    """Config value as a clean string; '' when the value means 'not set'."""
    if value is None:
        return ""
    if isinstance(value, float):
        # pandas turns an empty CSV cell into float('nan')
        if value != value:
            return ""
        return str(value)
    text = str(value).strip()
    if text.upper() in MISSING_TOKENS:
        return ""
    return text


def _is_set(value: Any) -> bool:
    return _clean(value) != ""


def _looks_like_path(value: str) -> bool:
    """True when a value is meant to be a filesystem path.

    ``eaffile`` may legitimately be a *resource name* ('EUR') that
    ``resolve_resource_file`` resolves against the resource folder, so a bare
    name must not be reported as a missing file.
    """
    if not value:
        return False
    if os.sep in value or value.startswith("~") or "/" in value:
        return True
    lowered = value.lower()
    return any(lowered.endswith(suffix) for suffix in _PATH_SUFFIXES)


def _resolve_policies(policies, problems: List[Problem]):
    """Accept a Policies object, a raw mapping, or None."""
    if policies is None:
        return default_policies()
    if isinstance(policies, Policies):
        return policies
    try:
        return load_policies(policies)
    except PolicyError as exc:
        for bad in exc.problems:
            problems.append(
                Problem(
                    config_key=bad.key,
                    configured_value=bad.value,
                    issue=bad.message,
                    suggestion="Correct the value in the policies block.",
                    category="policy",
                    stage="config",
                )
            )
        return default_policies()


def _ok(problems: Sequence[Problem]) -> bool:
    return not any(p.severity == "error" for p in problems)


def _severity_for(action: str) -> str:
    """'fail' -> error, anything else ('warn') -> warning."""
    return "error" if str(action).lower() == "fail" else "warning"


_emit = emit_message


# ======================================================================
# Header reading — one line, any of the usual compressions
def _first_data_line(path: str) -> str:
    """The header line, with '##' metadata skipped."""
    with open_text(path) as handle:
        for line in handle:
            if line.startswith("##") or not line.strip():
                continue
            return line.rstrip("\r\n")
    return ""


def read_summary_statistics_header(path: str, policies=None) -> Tuple[List[str], str]:
    """Return ``(header_names, separator)`` having read a single line.

    The names are the *raw* names as written in the file, so a repeated name is
    visible.  Polars renames the second occurrence to ``NAME_duplicated_0``,
    which is exactly the silent substitution the header stage exists to catch.
    """
    policies = policies if policies is not None else default_policies()
    line = _first_data_line(path)
    if not line:
        return [], "\t"
    separator = resolve_delimiter(
        path,
        str(policies.get("input.delimiter")),
        candidates=list(policies.get("input.delimiter_candidates")),
        minimum_columns=int(policies.get("input.delimiter_min_columns")),
        maximum_columns=int(policies.get("input.delimiter_max_columns")),
        sample_lines=int(policies.get("input.delimiter_sample_rows")),
    ).value
    header = next(csv.reader([line], delimiter=separator))
    return [name.strip() for name in header], separator


def _polars_header(path: str, separator: str) -> Optional[List[str]]:
    """What polars will actually call the columns, read with ``n_rows=0``."""
    if path.lower().endswith(".zip"):
        return None
    try:
        frame = pl.read_csv(
            path,
            separator=separator,
            n_rows=0,
            has_header=True,
            infer_schema_length=0,
            comment_prefix="##",
        )
    except Exception:
        return None
    return list(frame.columns)


# ======================================================================
# STAGE 1 — config only, nothing is read from the summary statistics
# ======================================================================
def _check_file(
    key: str,
    value: str,
    human: str,
    problems: List[Problem],
    required: bool,
) -> None:
    if key in ("eaffile", "infofile"):
        try:
            validate_external_resource_spec(value)
        except ValueError as exc:
            problems.append(
                Problem(
                    config_key=key,
                    configured_value=value,
                    issue=str(exc),
                    suggestion=(
                        "Use one existing file for all chromosomes or an explicit "
                        "path template containing {chromosome}."
                    ),
                    category="file_missing",
                    stage="config",
                )
            )
        return
    if not os.path.exists(value):
        problems.append(
            Problem(
                config_key=key,
                configured_value=value,
                issue="does not exist",
                suggestion="Check the path to %s.%s"
                % (human, " This file is mandatory." if required else ""),
                category="file_missing",
                stage="config",
            )
        )
        return
    try:
        empty = os.path.isfile(value) and os.path.getsize(value) == 0
    except OSError as exc:
        problems.append(
            Problem(
                config_key=key,
                configured_value=value,
                issue="could not be inspected (%s)" % exc,
                suggestion="Check permissions on %s." % human,
                category="file_missing",
                stage="config",
            )
        )
        return
    if empty:
        problems.append(
            Problem(
                config_key=key,
                configured_value=value,
                issue="is empty",
                suggestion="%s has zero bytes." % human.capitalize(),
                category="file_missing",
                stage="config",
            )
        )
        return
    if not os.access(value, os.R_OK):
        problems.append(
            Problem(
                config_key=key,
                configured_value=value,
                issue="cannot be read",
                suggestion="Check the permissions on %s." % human,
                category="file_missing",
                stage="config",
            )
        )
        return
    # A directory passes exists() and getsize(), so it has to be excluded
    # explicitly or it fails much later with IsADirectoryError.
    if not os.path.isfile(value):
        problems.append(
            Problem(
                config_key=key,
                configured_value=value,
                issue="is a directory, not a file",
                suggestion="Point %s at the file itself." % key,
                category="file_missing",
                stage="config",
            )
        )
        return
    # Opening a compressed file proves it is actually readable as what its
    # extension claims.  A truncated or half-copied .gz otherwise gets through
    # here and fails part-way through the parse, long after the run started.
    message = _first_bytes_readable(value)
    if message:
        problems.append(
            Problem(
                config_key=key,
                configured_value=value,
                issue=message,
                suggestion=(
                    "%s could not be opened for reading. If it was copied or "
                    "downloaded, check the transfer completed." % human.capitalize()
                ),
                category="file_unreadable",
                stage="config",
            )
        )


def _first_bytes_readable(path):
    """Try to read the first line, honouring the compression the name implies.

    Returns None when fine, or a short description of what went wrong.  Only the
    first block is touched, so this stays cheap on a ten-million-row file.
    """
    lowered = str(path).lower()
    try:
        if lowered.endswith((".gz", ".bgz")):
            import gzip
            with gzip.open(path, "rb") as handle:
                handle.read(4096)
        elif lowered.endswith((".xz", ".lzma")):
            import lzma
            with lzma.open(path, "rb") as handle:
                handle.read(4096)
        elif lowered.endswith(".bz2"):
            import bz2
            with bz2.open(path, "rb") as handle:
                handle.read(4096)
        elif lowered.endswith(".zip"):
            import zipfile
            with zipfile.ZipFile(path) as archive:
                names = archive.namelist()
                if not names:
                    return "is an empty zip archive"
                with archive.open(names[0]) as handle:
                    handle.read(4096)
        else:
            with open(path, "rb") as handle:
                handle.read(4096)
    except Exception as exc:                       # noqa: BLE001 - reported, not raised
        return "could not be read (%s: %s)" % (type(exc).__name__, exc)
    return None


def _check_external_column(
    file_key: str,
    column_key: str,
    cfg: Dict[str, Any],
    policies,
    problems: List[Problem],
) -> None:
    """An external file must actually contain the column it is asked to supply."""
    path = _clean(cfg.get(file_key))
    column = _clean(cfg.get(column_key))
    if not path or not column:
        return
    if not _looks_like_path(path):
        return
    try:
        matches = matching_external_resource_files(path)
    except ValueError:
        return
    if not matches:
        return
    inspected_path = str(matches[0])
    try:
        header, _sep = read_summary_statistics_header(inspected_path, policies)
    except Exception as exc:
        problems.append(
            Problem(
                config_key=file_key,
                configured_value=inspected_path,
                issue="header could not be read (%s)" % exc,
                suggestion="The file may be corrupt or use an unexpected format.",
                category="file_missing",
                stage="config",
            )
        )
        return
    if not header or column in header:
        return
    cutoff = float(policies.get("validation.fuzzy_match_cutoff"))
    close = difflib.get_close_matches(column, header, n=1, cutoff=cutoff)
    suggestion = (
        "Closest match in that file: '%s'." % close[0]
        if close
        else "Columns in that file: %s." % ", ".join(header[:12])
    )
    problems.append(
        Problem(
            config_key=column_key,
            configured_value=column,
            issue="is not a column of %s" % os.path.basename(path),
            suggestion=suggestion,
            category="external_column_missing",
            stage="config",
        )
    )


def _positive_int(
    key: str, value: Any, minimum: int, problems: List[Problem]
) -> None:
    text = _clean(value)
    if not text:
        return
    try:
        number = float(text)
    except (TypeError, ValueError):
        problems.append(
            Problem(
                config_key=key,
                configured_value=text,
                issue="is not a number",
                suggestion="Sample sizes must be whole numbers.",
                category="bad_value",
                stage="config",
            )
        )
        return
    if number != int(number):
        problems.append(
            Problem(
                config_key=key,
                configured_value=text,
                issue="is not a whole number",
                suggestion="Sample sizes must be whole numbers.",
                category="bad_value",
                stage="config",
            )
        )
        return
    if int(number) < minimum:
        problems.append(
            Problem(
                config_key=key,
                configured_value=text,
                issue="is below the smallest accepted sample size (%d)" % minimum,
                suggestion="See policy sample_size.min_value.",
                category="bad_value",
                stage="config",
            )
        )


def _first_existing(cfg: Dict[str, Any], *keys: str) -> str:
    for key in keys:
        value = _clean(cfg.get(key))
        if value:
            return value
    return ""


# ---------------------------------------------------------------------------
# required_inputs -- declarative, in config column names
# ---------------------------------------------------------------------------

def _resolve_virtual(cfg, token):
    """Resolve an '@name' alternative that is not a config column."""
    return False


def _alternative_text(alternative):
    """'chr_col + pos_col', or a plain key, or the prose for an '@' token."""
    return " + ".join(alternative)


def _check_required_inputs(cfg, requirements=None, policies=None):
    """Evaluate every required_inputs group against one config row."""
    groups = requirements
    if groups is None and policies is not None:
        groups = getattr(policies, "required_inputs", None)
    if groups is None:
        from .policies import REQUIRED_INPUTS as groups  # type: ignore
    problems = []
    for name in groups:
        spec = groups[name] or {}
        if not spec.get("required", True):
            continue
        alternatives = spec.get("any_of") or []
        satisfied = False
        for alternative in alternatives:
            ok = True
            for key in alternative:
                if key.startswith("@"):
                    if not _resolve_virtual(cfg, key):
                        ok = False
                        break
                elif not _is_set(cfg.get(key)):
                    ok = False
                    break
            if ok:
                satisfied = True
                break
        if satisfied:
            continue

        label = spec.get("label", name)
        options = "; or ".join(_alternative_text(a) for a in alternatives)
        # Show what the config currently says for each key involved, so the
        # user can see which one they left as NA.
        seen, current = [], []
        for alternative in alternatives:
            for key in alternative:
                if key.startswith("@") or key in seen:
                    continue
                seen.append(key)
                current.append("%s=%s" % (key, cfg.get(key, "(absent)")))
        problems.append(
            Problem(
                config_key=", ".join(seen) or name,
                configured_value=None,
                issue="no source of %s is configured" % label,
                suggestion=(
                    "Set %s. Currently: %s.%s"
                    % (options, ", ".join(current),
                       (" " + " ".join(str(spec["why"]).split()))
                       if spec.get("why") else "")
                ),
                category="missing_field",
                stage="config",
            )
        )
    return problems


def validate_config(cfg, policies=None, logger=None):
    # type: (Dict[str, Any], Any, Any) -> Tuple[bool, List[Problem]]
    """Stage 1 — everything that can be decided without opening the input file.

    Checks the mandatory config entries, the mandatory-with-alternatives rules
    for EAF / INFO / sample size, that every configured file exists and is not
    empty, that external files contain the column they are configured to
    supply, that scalar sample sizes are positive whole numbers, and that the
    policy block itself is valid.

    Returns ``(is_valid, problems)`` and never stops at the first problem.
    """
    problems = []  # type: List[Problem]
    policies = _resolve_policies(policies, problems)
    cfg = cfg or {}

    # ---- 1. what the dataset must supply ----------------------------
    #
    # Declared in the registry's `required_inputs:` block, in the CONFIG COLUMN
    # NAMES used in the config CSV.  A group is satisfied when every key of any
    # ONE alternative is set.  Nothing is read from disk yet: a config that
    # fails here is rejected before the sumstat file is opened.
    problems.extend(_check_required_inputs(cfg, policies=policies))

    # Reject NOW if any requirement is unmet.  Checking whether files exist or
    # whether columns are present is pointless -- and produces confusing
    # follow-on errors such as "eaffile does not exist" when eaffile is NA --
    # until the config names everything the pipeline needs.
    if problems:
        return False, problems

    # ---- 6. every configured file exists and is not empty -----------
    for key, human, required in FILE_CONFIG_KEYS:
        value = _clean(cfg.get(key))
        if not value:
            if required:
                continue  # already reported as a missing mandatory entry
            continue
        if not _looks_like_path(value):
            # A bare name such as 'EUR' is resolved later against the resource
            # folder by resolve_resource_file; it is not a path.
            continue
        _check_file(key, value, human, problems, required)

    resource_folder = _clean(cfg.get("resource_folder"))
    if resource_folder and not os.path.isdir(resource_folder):
        problems.append(
            Problem(
                config_key="resource_folder",
                configured_value=resource_folder,
                issue="is not an existing directory",
                suggestion="The reference resources are looked up under this folder.",
                category="file_missing",
                stage="config",
            )
        )

    # ---- 7. external files contain the column they supply -----------
    _check_external_column("eaffile", "eafcolumn", cfg, policies, problems)
    _check_external_column("infofile", "infocolumn", cfg, policies, problems)

    # ---- 8. scalar sample sizes -------------------------------------
    minimum = int(policies.get("sample_size.min_value"))
    for key in ("ncase", "ncontrol", "n", "total_n"):
        _positive_int(key, cfg.get(key), minimum, problems)

    # ---- 9. the output directory is usable --------------------------
    output_folder = _clean(cfg.get("output_folder"))
    if output_folder:
        probe = os.path.abspath(output_folder)
        existing = probe
        while existing and not os.path.exists(existing):
            parent = os.path.dirname(existing)
            if parent == existing:
                break
            existing = parent
        if not existing or not os.path.isdir(existing):
            problems.append(
                Problem(
                    config_key="output_folder",
                    configured_value=output_folder,
                    issue="cannot be created; no part of the path exists",
                    suggestion="Create the parent directory first.",
                    category="output",
                    stage="config",
                )
            )
        elif not os.access(existing, os.W_OK):
            problems.append(
                Problem(
                    config_key="output_folder",
                    configured_value=output_folder,
                    issue="is not writable (nearest existing directory is %s)" % existing,
                    suggestion="Results cannot be written there.",
                    category="output",
                    stage="config",
                )
            )

    valid = _ok(problems)
    if logger is not None:
        if valid:
            _emit(logger, "Configuration check passed; nothing has been read yet.")
        else:
            _emit(
                logger,
                format_problems(problems, title="Configuration check"),
                warn=True,
            )
    return valid, problems


# ======================================================================
# STAGE 2 — the header, and nothing but the header
# ======================================================================
def validate_header(cfg, sumstat_path, policies=None, logger=None):
    # type: (Dict[str, Any], str, Any, Any) -> Tuple[bool, List[Problem]]
    """Stage 2 — every configured column name is checked against the header.

    Reads one line.  Catches names that are absent, names that differ only in
    case or surrounding whitespace, near misses (with a suggestion), two config
    keys resolving to the same column, and a column name repeated in the file
    itself.
    """
    problems = []  # type: List[Problem]
    policies = _resolve_policies(policies, problems)
    cfg = cfg or {}

    path = _clean(sumstat_path) or _clean(cfg.get("sumstat_file"))
    if not path:
        problems.append(
            Problem(
                config_key="sumstat_file",
                configured_value=None,
                issue="no summary statistics file was given",
                suggestion="Nothing could be checked.",
                category="missing_key",
                stage="header",
            )
        )
        return False, problems
    if not os.path.exists(path):
        problems.append(
            Problem(
                config_key="sumstat_file",
                configured_value=path,
                issue="does not exist",
                suggestion="The header could not be read.",
                category="file_missing",
                stage="header",
            )
        )
        return False, problems

    declared_delimiter = _clean(cfg.get("delimiter"))
    if declared_delimiter and declared_delimiter.lower() != "auto":
        detected = detect_delimiter(
            path,
            candidates=list(policies.get("input.delimiter_candidates")),
            minimum_columns=int(policies.get("input.delimiter_min_columns")),
            maximum_columns=int(policies.get("input.delimiter_max_columns")),
            sample_lines=int(policies.get("input.delimiter_sample_rows")),
            comment_prefix=(
                "##" if bool(policies.get("input.strip_double_hash_lines")) else None
            ),
            fail_policy="unknown",
        )
        if (
            detected.kind == "delimiter"
            and detected.value != delimiter_character(declared_delimiter.lower())
        ):
            action = str(policies.get("validation.declaration_mismatch_action"))
            message = (
                "DECLARATION MISMATCH: sample sheet declares delimiter %r, but "
                "automatic detection found %r. Policy "
                "validation.declaration_mismatch_action=%r; the declared delimiter "
                "remains authoritative."
                % (declared_delimiter.lower(), detected.value, action)
            )
            emit_high_visibility_warning(logger, message)
            if action == "fail":
                problems.append(
                    Problem(
                        config_key="delimiter",
                        configured_value=declared_delimiter,
                        issue="disagrees with automatic delimiter detection",
                        suggestion=(
                            "Correct the sample-sheet delimiter, or set "
                            "validation.declaration_mismatch_action to 'warn' to "
                            "continue with the declaration."
                        ),
                        category="bad_value",
                        stage="header",
                    )
                )

    try:
        header, separator = read_summary_statistics_header(path, policies)
    except Exception as exc:
        problems.append(
            Problem(
                config_key="sumstat_file",
                configured_value=path,
                issue="header could not be read (%s)" % exc,
                suggestion="The file may be truncated, corrupt or compressed oddly.",
                category="file_unreadable",
                stage="header",
            )
        )
        return False, problems

    if not header:
        problems.append(
            Problem(
                config_key="sumstat_file",
                configured_value=path,
                issue="has no header line",
                suggestion="The file looks empty once '##' metadata is skipped.",
                category="file_unreadable",
                stage="header",
            )
        )
        return False, problems

    # ---- repeated column names in the file itself -------------------
    # Polars renames the second occurrence to NAME_duplicated_0, so the config
    # silently gets the first one.  (The current io.py detectors look for an
    # 'Unnamed:' prefix and a '_duplicated' *prefix*, both pandas conventions
    # that polars never produces; they can never fire.)
    duplicate_severity = _severity_for(policies.get("validation.on_duplicate_header"))
    for name, count in Counter(header).items():
        if count > 1:
            problems.append(
                Problem(
                    config_key="sumstat_file",
                    configured_value=None,
                    issue="the file has %d columns called '%s'" % (count, name),
                    suggestion=(
                        "Polars keeps the first and renames the rest to "
                        "'%s_duplicated_0', so a config naming '%s' silently gets the "
                        "first one." % (name, name)
                    ),
                    category="duplicate_header",
                    stage="header",
                    severity=duplicate_severity,
                    standalone=True,
                )
            )

    blank = [index for index, name in enumerate(header) if not name.strip()]
    if blank:
        problems.append(
            Problem(
                config_key="sumstat_file",
                configured_value=None,
                issue="the header has %d unnamed column(s) (position %s)"
                % (len(blank), ", ".join(str(i + 1) for i in blank)),
                suggestion="This usually means the delimiter was guessed wrongly.",
                category="duplicate_header",
                stage="header",
                severity="warning",
                standalone=True,
            )
        )

    # ---- one lookup table per matching rule -------------------------
    exact = set(header)
    loose = {}  # type: Dict[str, List[str]]
    for name in header:
        loose.setdefault(name.strip().lower(), []).append(name)

    cutoff = float(policies.get("validation.fuzzy_match_cutoff"))

    # chr_col / pos_col may legitimately be derived from a combined column.
    chr_pos = _clean(cfg.get("chr_pos_col"))
    derived_coordinates = bool(chr_pos) and chr_pos in exact

    by_value = OrderedDict()  # type: Dict[str, List[str]]
    for key in COLUMN_CONFIG_KEYS:
        value = _clean(cfg.get(key))
        if not value:
            continue  # a normalized missing value means this column was not supplied
        if derived_coordinates and key in ("chr_col", "pos_col"):
            continue
        by_value.setdefault(value, []).append(key)
        if value in exact:
            continue
        candidates = loose.get(value.strip().lower())
        if candidates:
            suggestion = "Did you mean '%s'?  (only the case or surrounding whitespace differs)" % (
                candidates[0],
            )
        else:
            close = difflib.get_close_matches(value, header, n=1, cutoff=cutoff)
            suggestion = (
                "Closest match in file: '%s'" % close[0]
                if close
                else "No similar column name."
            )
        problems.append(
            Problem(
                config_key=key,
                configured_value=value,
                issue="not found",
                suggestion=suggestion,
                category="column_not_found",
                stage="header",
            )
        )

    # ---- two config keys on one column ------------------------------
    ambiguous_severity = _severity_for(
        policies.get("validation.on_ambiguous_column_mapping")
    )
    for value, keys in by_value.items():
        if len(keys) < 2:
            continue
        joined = " and ".join(keys)
        problems.append(
            Problem(
                config_key=", ".join(keys),
                configured_value=None,
                issue="%s are both set to '%s'" % (joined, value),
                suggestion=(
                    "Reading the same column twice ends in a polars duplicate-name "
                    "error that names the column, not the config keys."
                ),
                category="ambiguous_mapping",
                stage="header",
                severity=ambiguous_severity,
                standalone=True,
            )
        )

    # ---- cross-check what polars will actually see ------------------
    effective = _polars_header(path, separator)
    if effective is not None and len(effective) != len(header):
        problems.append(
            Problem(
                config_key="input.delimiter",
                configured_value=repr(separator),
                issue=(
                    "splits the header into %d columns but polars reads %d"
                    % (len(header), len(effective))
                ),
                suggestion="Set input.delimiter explicitly if the guess is wrong.",
                category="file_unreadable",
                stage="header",
                severity="warning",
            )
        )

    valid = _ok(problems)
    if logger is not None:
        if valid:
            _emit(
                logger,
                "Header check passed: all %d configured column names are in the file."
                % len(by_value),
            )
        else:
            _emit(
                logger,
                format_problems(
                    problems,
                    title="Configuration check for %s"
                    % (_clean(cfg.get("gwas_outputname")) or os.path.basename(path)),
                    columns_present=header,
                    source_name=os.path.basename(path),
                    footer="Nothing was read beyond the header. Fix the config and re-run.",
                ),
                warn=True,
            )
    return valid, problems


# ======================================================================
# STAGE 3 — needs the parsed data
# ======================================================================
def validate_content(cfg, df, policies=None, logger=None):
    # type: (Dict[str, Any], pl.DataFrame, Any, Any) -> Tuple[bool, List[Problem]]
    """Stage 3 — the checks that only the parsed frame can answer.

    A configured column that exists but is entirely null; a numeric column that
    arrived as text because one cell would not parse; and zero variants
    surviving the basic coordinate and allele checks.
    """
    problems = []  # type: List[Problem]
    policies = _resolve_policies(policies, problems)
    cfg = cfg or {}

    if df is None:
        problems.append(
            Problem(
                config_key="sumstat_file",
                configured_value=None,
                issue="no data frame was produced by the read",
                suggestion="The read step failed before content could be checked.",
                category="no_variants",
                stage="content",
            )
        )
        return False, problems

    if df.height == 0:
        problems.append(
            Problem(
                config_key="sumstat_file",
                configured_value=_clean(cfg.get("sumstat_file")) or None,
                issue="was read but holds no variants",
                suggestion="Check the delimiter and the '##' metadata handling.",
                category="no_variants",
                stage="content",
            )
        )
        return False, problems

    columns = set(df.columns)

    # ---- configured but entirely null -------------------------------
    checked = []
    owner = {}  # type: Dict[str, str]
    for key in COLUMN_CONFIG_KEYS:
        value = _clean(cfg.get(key))
        if value and value in columns:
            if value not in owner:
                owner[value] = key
                checked.append(value)
    if checked:
        # de-duplicated, or two identical aliases raise polars DuplicateError
        null_counts = df.select(
            [pl.col(name).null_count().alias(name) for name in checked]
        ).row(0)
        for name, nulls in zip(checked, null_counts):
            if nulls == df.height:
                problems.append(
                    Problem(
                        config_key=owner[name],
                        configured_value=name,
                        issue="is present in the file but every one of its %d values is missing"
                        % df.height,
                        suggestion="The column exists but carries no data.",
                        category="all_null",
                        stage="content",
                    )
                )

    # ---- numeric column that arrived as text ------------------------
    for key in NUMERIC_COLUMN_KEYS:
        name = _clean(cfg.get(key))
        if not name or name not in columns:
            continue
        dtype = df.schema[name]
        if dtype not in (pl.Utf8, pl.String):
            continue
        series = df.get_column(name)
        cast = series.cast(pl.Float64, strict=False)
        unparseable = cast.null_count() - series.null_count()
        if unparseable <= 0:
            continue
        examples = (
            df.lazy()
            .filter(
                pl.col(name).is_not_null()
                & pl.col(name).cast(pl.Float64, strict=False).is_null()
            )
            .select(pl.col(name).unique().head(5))
            .collect()
            .get_column(name)
            .to_list()
        )
        problems.append(
            Problem(
                config_key=key,
                configured_value=name,
                issue="must hold numbers but %d value(s) will not parse" % unparseable,
                suggestion="Unparseable values include: %s."
                % ", ".join(repr(v) for v in examples),
                category="not_numeric",
                stage="content",
            )
        )

    # ---- zero variants surviving the basic checks -------------------
    # The normal pipeline reaches this function only after the input reader
    # has normalized and filtered these fields.  Its private marker plus exact
    # canonical dtypes make that contract checkable without scanning rows.
    # Direct callers without the contract retain the complete validation.
    if has_canonical_variant_columns(df, cfg):
        if logger is not None:
            _emit(
                logger,
                "Coordinate and allele content checks reused the completed "
                "dataset-level validation; no second row scan was required.",
            )
    else:
        chr_col = _clean(cfg.get("chr_col"))
        pos_col = _clean(cfg.get("pos_col"))
        ea_col = _clean(cfg.get("ea_col"))
        oa_col = _clean(cfg.get("oa_col"))
        allowed = [str(c).upper() for c in policies.get("chromosome.allowed")]
        pattern = str(policies.get("allele.pattern"))
        min_position = int(policies.get("position.min_value"))

        mask = pl.lit(True)
        applied = []
        if chr_col in columns:
            mask = mask & (
                pl.col(chr_col)
                .cast(pl.Utf8, strict=False)
                .str.strip_chars()
                .str.replace(r"(?i)^chr", "", literal=False)
                .str.to_uppercase()
                .is_in(allowed)
            )
            applied.append("chromosome")
        if pos_col in columns:
            mask = mask & (
                pl.col(pos_col)
                .cast(pl.Float64, strict=False)
                .cast(pl.Int64, strict=False)
                >= min_position
            )
            applied.append("position")
        if ea_col in columns and oa_col in columns:
            mask = (
                mask
                & pl.col(ea_col)
                .cast(pl.Utf8, strict=False)
                .str.to_uppercase()
                .str.contains(pattern)
                & pl.col(oa_col)
                .cast(pl.Utf8, strict=False)
                .str.to_uppercase()
                .str.contains(pattern)
            )
            applied.append("alleles")
        if applied:
            surviving = int(df.select(mask.fill_null(False).sum()).item())
            if surviving == 0:
                problems.append(
                    Problem(
                        config_key="chr_col, pos_col, ea_col, oa_col",
                        configured_value=None,
                        issue="none of the %d variants pass the basic %s checks"
                        % (df.height, " / ".join(applied)),
                        suggestion=(
                            "Check chromosome.allowed, position.min_value and "
                            "allele.pattern, and that the columns are mapped correctly."
                        ),
                        category="no_variants",
                        stage="content",
                    )
                )

    valid = _ok(problems)
    if logger is not None:
        if valid:
            _emit(
                logger,
                "Content check passed on %d variants." % df.height,
            )
        else:
            _emit(logger, format_problems(problems, title="Content check"), warn=True)
    return valid, problems


# ======================================================================
# Report generation — the message is generated, not hand-written
# ======================================================================
def format_problems(
    problems,
    title=None,
    columns_present=None,
    source_name=None,
    footer=None,
):
    # type: (Sequence[Problem], Optional[str], Optional[Sequence[str]], Optional[str], Optional[str]) -> str
    """Render a list of :class:`Problem` records as the plan 2.3 report."""
    problems = list(problems or [])
    if not problems:
        return ""

    errors = [p for p in problems if p.severity == "error"]
    count = len(errors) if errors else len(problems)
    noun = "problem" if count == 1 else "problems"
    lines = []
    if title:
        lines.append("%s - %d %s found." % (title, count, noun))
        lines.append("")

    # Sections in registry order, then anything unexpected, in first-seen order.
    order = [c for c in CATEGORY_HEADINGS if any(p.category == c for p in problems)]
    for problem in problems:
        if problem.category not in order:
            order.append(problem.category)

    for category in order:
        group = [p for p in problems if p.category == category]
        if not group:
            continue
        heading = CATEGORY_HEADINGS.get(category, "Other problems:")
        lines.append("  %s" % heading)
        lines.append("")
        key_width = max(len(p.config_key) for p in group)
        value_width = max(len(p.rendered_value()) for p in group)
        for problem in group:
            marker = "" if problem.severity == "error" else "(warning) "
            lines.append("    %s%s" % (marker, problem.line(key_width, value_width)))
        lines.append("")

    if columns_present:
        where = " in %s" % source_name if source_name else ""
        lines.append(
            "  Columns actually present%s (%d):" % (where, len(columns_present))
        )
        lines.append("    %s" % ", ".join(str(c) for c in columns_present))
        lines.append("")

    if footer:
        lines.append("  %s" % footer)

    return "\n".join(lines).rstrip() + "\n"


# ======================================================================
