# Named defaults for the SuSiE workflow. All operational and scientific
# thresholds are centralized here and exposed through get_susie_defaults().
# The 0.95 credible-set coverage is a fixed scientific requirement.

get_susie_defaults <- function() {
  list(
    credible_set_coverage = 0.95,
    credible_set_tolerance = 1e-3,
    min_abs_corr = 0.5,
    ld_eigenvalue_tolerance = 1e-4,
    ld_eigenvalue_floor = 1e-8,
    ld_lambda_warning = 0.01,
    ld_lambda_failure = 0.1,
    ld_repair_max_change = 0.05,
    lp_threshold = 7.3,
    max_causal_components = 10L,
    main_max_iter = 100L,
    recovery_max_iter = 600L,
    repaired_max_iter = 300L,
    reduced_l_max = 5L,
    ld_retry_multiplier = 2,
    ld_retry_add_seconds = 60L,
    recovery_timeout_multiplier = 4,
    ld_repair_timeout_multiplier = 3,
    repaired_timeout_multiplier = 3,
    ld_timeout_seconds = 180L,
    susie_timeout_seconds = 180L,
    plink_timeout_seconds = 500L,
    process_poll_seconds = 0.25,
    process_terminate_grace_seconds = 0.5,
    stderr_tail_lines = 50L,
    progress_digits = 1L,
    pipeline_stage_total = 5L,
    memory_used_threshold_pct = 96,
    memory_check_interval_seconds = 10,
    memory_max_wait_seconds = 6 * 3600,
    min_ram_per_worker_gb = 4,
    reserve_cores = 1L,
    workers = "auto",
    verbose = TRUE,
    skip_mhc = TRUE,
    minimum_position = 1L,
    mhc_chromosome = "6",
    mhc_start = 25e6,
    mhc_end = 35e6,
    genome_build = "GRCh37",
    supported_genome_builds = c("GRCh37", "GRCh38"),
    plot_min_pip_label = 0.01,
    plot_background_size = 0.01,
    plot_background_alpha = 0.15,
    plot_cs_size = 1,
    plot_cs_alpha = 0.2,
    plot_max_ld_dimension = 5000L,
    plot_width = 11,
    plot_height = 12,
    plot_dpi = 300L,
    plot_ld_palette_colors = 256L,
    plot_legend_gradient_points = 100L,
    plot_legend_title_size = 8,
    plot_legend_text_size = 7,
    plot_legend_key_size_cm = 0.3,
    plot_legend_scale = 0.55,
    plot_credible_set_legend_size = 3,
    plot_labels_per_credible_set = 5L,
    plot_large_locus_threshold = 5000L,
    plot_medium_locus_threshold = 2000L,
    plot_large_locus_scale = 0.6,
    plot_medium_locus_scale = 0.8,
    plot_label_lift = 0.03,
    plot_label_size = 3,
    plot_label_segment_alpha = 0.7,
    plot_label_segment_width = 0.3,
    plot_panel_heights = c(2, 1, 1),
    plot_panel_widths = c(5, 0.8),
    macos_available_memory_fraction = 0.25,
    meminfo_read_lines = 50L
  )
}

SUSIE_DEFAULTS <- get_susie_defaults()
