#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import sys

from pydantic import ValidationError

from postgwas.cli.compute import get_compute_parser
from postgwas.core.errors import ConfigurationError, MissingRequiredArgumentsError
from postgwas.core.ui import (
    print_screen_message,
    AlignedRichHelpFormatter,
    format_cli_examples,
    help_with_default,
    mark_cli_required_help,
)
from postgwas.config import load_configuration

# =========================================================
# Shared parsers
# ---------------------------------------------------------
# NOTE: These modules must exist in your postgwas project
# =========================================================
from postgwas.cli.common import (
    get_common_out_parser,
    get_common_imputation_parser,
    get_imputation_population_parser,
)
# NOTE: These modules must exist in your postgwas project
from postgwas.core.execution.runtime import validate_path
from postgwas.modules.imputation.service import run_sumstat_imputation_direct


# ---------------------------------------------------------
# DIRECT-MODE INPUT PARSER
# ---------------------------------------------------------
def get_imputation_direct_inputs_parser(add_help=False):
    """
    Inputs required for DIRECT imputation mode.
    (Output directory handled by get_common_out_parser)
    """
    # NOTE: add_help=False is used here so this parser doesn't
    # conflict when its arguments are grouped into the main parser.
    parser = argparse.ArgumentParser(add_help=add_help)

    grp = parser.add_argument_group("Formatter input")
    grp.add_argument(
        "--pred-ld-input-directory",
        dest="pred_ld_input_directory",
        metavar="PATH",
        default=argparse.SUPPRESS,
        type=validate_path(must_exist=True, must_be_dir=True),
        help=(
            "Directory containing per-chromosome formatted summary stats "
            "in PRED-LD compatible format (generated by postgwas formatter)."
        ),
    )
    controls = parser.add_argument_group("Configuration")
    controls.add_argument(
        "--run-config",
        metavar="PATH",
        default=argparse.SUPPRESS,
        type=validate_path(must_exist=True, must_be_file=True),
        help=(
            "YAML file containing imputation or full-run settings. Explicit "
            "command-line values override matching YAML values."
        ),
    )
    return parser


def get_imputation_genome_build_parser(add_help=False):
    """Expose the reference-build declaration without an argparse default."""
    configuration = load_configuration()
    module = configuration.modules.imputation
    parser = argparse.ArgumentParser(add_help=add_help)
    group = parser.add_argument_group("Genome coordinates")
    group.add_argument(
        "--genome-build",
        choices=list(configuration.resources.genomes),
        metavar="BUILD",
        default=argparse.SUPPRESS,
        help=help_with_default(
            "Genome build explicitly declared for the PRED-LD reference; it "
            "must match the harmonised GWAS-VCF",
            module.genome_build,
        ),
    )
    return parser


# =========================================================
# MAIN CLI (DIRECT-ONLY, NO PIPELINE)
# =========================================================
def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="postgwas imputation",
        usage="postgwas imputation --pred-ld-input-directory PATH [options]",
        description="Impute missing summary statistics with the configured PRED-LD workflow.",
        epilog=format_cli_examples(
            (
                "Run PRED-LD imputation from formatter output:",
                "postgwas imputation",
                (
                    "--pred-ld-input-directory formatted/pred_ld",
                    "--imputation-ld-reference reference/pred_ld",
                    "--resource-directory resources",
                    "--genome-build GRCh37",
                    "--population EUR",
                    "--dataset-id STUDY",
                    "--output-directory results",
                ),
            ),
            (
                "Export the imputation pipeline configuration:",
                "postgwas config export",
                ("--pipeline imputation", "--style full", "--output imputation_pipeline.yaml"),
            ),
        ),
        formatter_class=AlignedRichHelpFormatter,
        parents=[
            get_compute_parser(),
            get_common_out_parser(),
            get_imputation_population_parser(),
            get_common_imputation_parser(),
            get_imputation_genome_build_parser(),
            get_imputation_direct_inputs_parser(),
        ],
    )
    mark_cli_required_help(
        parser,
        (
            "pred_ld_input_directory",
            "imputation_ld_reference",
            "resource_directory",
            "genome_build",
            "dataset_id",
            "output_directory",
        ),
    )
    return parser


def main(argv=None) -> int:
    parser = build_parser()

    # If no arguments provided → show help
    arguments = sys.argv[1:] if argv is None else list(argv)
    if not arguments:
        parser.print_help()
        return 0

    # Parse arguments
    args = parser.parse_args(arguments)

    # -----------------------------------------------------
    # Run the DIRECT workflow
    # -----------------------------------------------------
    # Call the main imputation function with parsed arguments
    try:
        run_sumstat_imputation_direct(args)
    except (
        ConfigurationError,
        MissingRequiredArgumentsError,
        OSError,
        RuntimeError,
        ValidationError,
        ValueError,
    ) as exc:
        print_screen_message(
            "error", "Summary-statistic imputation stopped.\n"
            "Reason: %s\nNo completed imputation result was published." % exc,
            stderr=True,
        )
        return 1
    return 0
# =========================================================
# Entry point
# =========================================================
if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "build_parser",
    "get_imputation_direct_inputs_parser",
    "get_imputation_genome_build_parser",
    "main",
]
