#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import sys

from postgwas.cli.compute import get_compute_parser
from postgwas.core.ui import (
    AlignedRichHelpFormatter,
    format_cli_examples,
)

# =========================================================
# Shared parsers
# ---------------------------------------------------------
# NOTE: These modules must exist in your postgwas project
# =========================================================
from postgwas.cli.common import (
    get_common_out_parser,
    get_common_imputation_parser,
    get_bcftools_binary_parser,
    get_imputation_population_parser,
)
# NOTE: These modules must exist in your postgwas project
from postgwas.core.execution.runtime import validate_path
from postgwas.modules.imputation.service import run_sumstat_imputation_direct


# ---------------------------------------------------------
# DIRECT-MODE INPUT PARSER
# ---------------------------------------------------------
def get_imputation_direct_inputs_parser(add_help=False):
    """
    Inputs required for DIRECT imputation mode.
    (Output directory handled by get_common_out_parser)
    """
    # NOTE: add_help=False is used here so this parser doesn't
    # conflict when its arguments are grouped into the main parser.
    parser = argparse.ArgumentParser(add_help=add_help)

    grp = parser.add_argument_group("Formatter input")
    grp.add_argument(
        "--pred-ld-input-directory",
        dest="pred_ld_input_directory",
        metavar="PATH",
        required=True,
        type=validate_path(must_exist=True, must_be_dir=True),
        help=(
            "Directory containing per-chromosome formatted summary stats "
            "in PRED-LD compatible format (generated by postgwas formatter)."
        ),
    )
    return parser


# =========================================================
# MAIN CLI (DIRECT-ONLY, NO PIPELINE)
# =========================================================
def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="postgwas imputation",
        usage="postgwas imputation --pred-ld-input-directory PATH [options]",
        description="Impute missing summary statistics with the configured PRED-LD workflow.",
        epilog=format_cli_examples(
            (
                "Run PRED-LD imputation from formatter output:",
                "postgwas imputation",
                (
                    "--pred-ld-input-directory formatted/pred_ld",
                    "--imputation-ld-reference reference/pred_ld",
                    "--resource-directory resources",
                    "--population EUR",
                    "--dataset-id STUDY",
                    "--output-directory results",
                ),
            ),
            (
                "Export the imputation pipeline configuration:",
                "postgwas config export",
                ("--pipeline imputation", "--style full", "--output imputation_pipeline.yaml"),
            ),
        ),
        formatter_class=AlignedRichHelpFormatter,
        parents=[
            get_compute_parser(),
            get_common_out_parser(),
            get_imputation_population_parser(),
            get_common_imputation_parser(),
            get_imputation_direct_inputs_parser(),
            get_bcftools_binary_parser(),
        ],
    )
    return parser


def main():
    parser = build_parser()

    # If no arguments provided → show help
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(0)

    # Parse arguments
    args = parser.parse_args()

    # -----------------------------------------------------
    # Run the DIRECT workflow
    # -----------------------------------------------------
    # Call the main imputation function with parsed arguments
    run_sumstat_imputation_direct(args)
# =========================================================
# Entry point
# =========================================================
if __name__ == "__main__":
    main()


__all__ = ["build_parser", "get_imputation_direct_inputs_parser", "main"]
