#!/usr/bin/env python3
"""
PostGWAS — MAGMA Gene & Geneset Analysis (Step 5)
Supports:
  • DIRECT MODE:   Run MAGMA on existing MAGMA-ready input files
  • PIPELINE MODE: Harmonisation → LD Blocks → QC Filter → Formatter → MAGMA

This CLI is fully harmonised with your PostGWAS architecture.
"""

import argparse
import sys
from pathlib import Path
from rich_argparse import RichHelpFormatter

# ---------------------------------------------------------
# Shared CLI components (must accept add_help=False)
# ---------------------------------------------------------
from postgwas.clis.common_cli import (
    get_defaultresourse_parser,
    get_genomeversion_parser,
    get_common_out_parser,
    get_common_magma_assoc_parser,
    get_magma_binary_parser)



# MAGMA engine
from postgwas.gene_assoc.workflows import run_magma_direct


# =====================================================================
#   MAGMA Association Parser (Step 5)
# =====================================================================
def get_magma_assoc_parser(add_help=False):
    """
    Parser containing only MAGMA association-related arguments.
    This is parent-safe and can be inserted into direct/pipeline mode.
    """
    parser = argparse.ArgumentParser(add_help=add_help)
    group = parser.add_argument_group("MAGMA Association Arguments")


    group.add_argument(
        "--snp_loc_file",
        metavar="",
        help="SNP location file (.loc) generated by PostGWAS formatter.",
    )

    group.add_argument(
        "--pval_file",
        metavar="",
        help="MAGMA *.pval input file. generated by PostGWAS formatter.",
    )

    return parser



# =====================================================================
#   MAIN CLI ENTRY
# =====================================================================
def main():
    # --------------------------------------------------------
    # Top-level parser (MAGMA Direct Mode Only)
    # --------------------------------------------------------
    parser = argparse.ArgumentParser(
        prog="magma",
        description="MAGMA Gene & Geneset Analysis — Direct mode: Run MAGMA on existing MAGMA-ready files.",
        formatter_class=RichHelpFormatter,
        parents=[
            # Parsers required for a MAGMA Direct run:
            get_defaultresourse_parser(),
            get_magma_binary_parser(),
            get_genomeversion_parser(),
            get_common_out_parser(),
            get_magma_assoc_parser(add_help=False),
            get_common_magma_assoc_parser()
        ]
    )
    
    # --------------------------------------------------------
    # EXECUTION
    # --------------------------------------------------------
    
    # If no arguments provided → show help
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(0)

    # Parse all arguments
    args = parser.parse_args()
    run_magma_direct(args) 

if __name__ == "__main__":
    main()