#!/usr/bin/env python3
"""
PostGWAS — MAGMA Gene & Geneset Analysis (Step 5)
Supports:
  • DIRECT MODE:   Run MAGMA on existing MAGMA-ready input files
  • PIPELINE MODE: Harmonisation → LD Blocks → QC Filter → Formatter → MAGMA

This CLI is fully harmonised with your PostGWAS architecture.
"""

import argparse
import sys
from pathlib import Path
from rich_argparse import RichHelpFormatter

# ---------------------------------------------------------
# Shared CLI components (must accept add_help=False)
# ---------------------------------------------------------
from postgwas.clis.common_cli import (
    get_defaultresourse_parser,
    get_genomeversion_parser,
    get_inputvcf_parser,
    get_common_out_parser,
    get_common_magma_assoc_parser,
    get_common_sumstat_filter_parser,
    get_magma_binary_parser
)
from postgwas.annot_ldblock.cli import get_annot_ldblock_parser
from postgwas.formatter.cli import get_formatter_parser
from postgwas.harmonisation.cli import get_harmonisation_parser



# MAGMA engine
from postgwas.gene_assoc.workflows import run_magma_direct, run_magma_pipeline


# =====================================================================
#   MAGMA Association Parser (Step 5)
# =====================================================================
def get_magma_assoc_parser(add_help=False):
    """
    Parser containing only MAGMA association-related arguments.
    This is parent-safe and can be inserted into direct/pipeline mode.
    """
    parser = argparse.ArgumentParser(add_help=add_help)
    group = parser.add_argument_group("MAGMA Association Arguments")


    group.add_argument(
        "--snp_loc_file",
        metavar="",
        help="SNP location file (.loc) generated by PostGWAS formatter.",
    )

    group.add_argument(
        "--pval_file",
        metavar="",
        help="MAGMA *.pval input file. generated by PostGWAS formatter.",
    )

    return parser



# =====================================================================
#   MAIN CLI ENTRY
# =====================================================================
def main():

    top = argparse.ArgumentParser(
        prog="magma",
        description="MAGMA Gene & Geneset Analysis — Direct mode or Full PostGWAS Pipeline.",
        formatter_class=RichHelpFormatter,
    )

    sub = top.add_subparsers(dest="mode", help="Choose execution mode")

    # --------------------------------------------------------
    # DIRECT MODE
    # --------------------------------------------------------
    direct = sub.add_parser(
        "direct",
        help="Run MAGMA on existing MAGMA-ready files.",
        parents=[
            get_defaultresourse_parser(),
            get_magma_binary_parser(),
            get_genomeversion_parser(),
            get_common_out_parser(),
            get_magma_assoc_parser(add_help=False),
            get_common_magma_assoc_parser()
        ],
        formatter_class=RichHelpFormatter,
    )
    direct.set_defaults(func=run_magma_direct)

    # --------------------------------------------------------
    # PIPELINE MODE (Steps 1–5)
    # --------------------------------------------------------
    pipeline = sub.add_parser(
        "pipeline",
        help="Run full PostGWAS pipeline → Harmonisation → LD Blocks → QC → Formatter → MAGMA",
        parents=[
            get_defaultresourse_parser(),
            get_magma_binary_parser(),
            get_harmonisation_parser(),
            get_annot_ldblock_parser(),
            get_common_sumstat_filter_parser(add_help=False),
            get_formatter_parser(),
            get_common_magma_assoc_parser(add_help=False),
            get_common_out_parser(),
        ],
        formatter_class=RichHelpFormatter,
    )
    pipeline.set_defaults(func=run_magma_pipeline)

    # --------------------------------------------------------
    # EXECUTION
    # --------------------------------------------------------
    args = top.parse_args()

    if args.mode == "direct" and len(sys.argv) == 2:
        top.parse_args(["direct", "--help"])
        sys.exit(0)

    if args.mode == "pipeline" and len(sys.argv) == 2:
        top.parse_args(["pipeline", "--help"])
        sys.exit(0)

    if hasattr(args, "func"):
        args.func(args)
    else:
        top.print_help()



if __name__ == "__main__":
    main()
